version: "3"

name: tigerbeetle_api

services:
  tigerbeetle:
    image: ghcr.io/tigerbeetle/tigerbeetle:0.15.3
    volumes:
      - tigerbeetle:/data
    ports:
      - 127.0.0.1:3033:3033
    environment:
      - TB_ADDRESSES=0.0.0.0:3033
    command: start /data/0_0.tigerbeetle

volumes:
  tigerbeetle:
