version: "3"

vars:
  BINFILE: tigerbeetle_rest_server

tasks:
  default: task --list-all
  dev: 
    cmds: 
      - task -p dev:run
  start:
    cmds:
      - task: build
      - task: build:start
  build:
    cmds:
      - task: build:run

  # Docker
  docker:start: cd docker_dev; docker compose up -d
  docker:stop: cd docker_dev; docker compose stop
  docker:setup: cd docker_dev; docker compose pull && docker compose run tigerbeetle format --cluster=0 --replica=0 --replica-count=1 /data/0_0.tigerbeetle
  docker:remove: cd docker_dev;  docker compose down -v --remove-orphans

  # Internal
  build:start: ./{{.BINFILE}}
  build:run:
    internal: true
    cmds:
      - go build -o {{.BINFILE}}  
  dev:run: task dev:run:watch
  dev:run:watch:
    watch: true
    sources:
      - "**/*.go"
    cmds:
      - task: build:run
      - task build:start