name: Go

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
    - name: Install Task
      uses: arduino/setup-task@v2
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - name: Preinstall go protobuf dependencies
      run: go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28 && go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
    - name: Build
      run: task build
