name: Go

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - name: Lint with gofmt
      run: test -z $(gofmt -l .)
    - name: Build
      run: make build
