name: Publish-Docker

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag (e.g., v1.0.0 or latest)'
        required: false
        default: 'latest'
      branch:
        description: 'Branch to build from'
        required: false
        default: 'main'

permissions:
  contents: read
  packages: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} 
        # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
        # Lint the code with gofmt
      - name: Lint with gofmt
        run: test -z "$(gofmt -l .)"
        # Build the Go application
      - name: Build the application
        run: go build -o tigerbeetle_api .
  build-and-publish:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} 
        # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # GitHub automatically provides a GITHUB_TOKEN secret to authenticate
          password: ${{ secrets.GITHUB_TOKEN }}
        # Setup env for building docker images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
          # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          # Set to true to push the image to the registry
          push: true
          # Define the tags for the image
          tags: |
            ghcr.io/${{ github.repository_owner }}/tigerbeetle_api:latest
            ghcr.io/${{ github.repository_owner }}/tigerbeetle_api:${{ github.sha }}
        # (Optional) Display Docker image details
      - name: Show Docker images
        run: docker images